import Header from '@/components/Header'
import './globals.css'
import 'simple-icons-font/font/simple-icons.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Hello World',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={inter.className+" bg-pink-50"}>

        <Header/>

        <main className='min-h-screen'>
          {children}
        </main>

        <footer className='text-center p-5'>
          <span className='inline-block'>© Copyright 2023 tomo0611.</span> <span className='inline-block'>All Rights Reserved.</span>
        </footer>
      </body>
    </html>
  )
}
